//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WowArmory.Core.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WowArmory.Core.Languages.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ©2010-2011 Christian Krueger. All rights reserved..
        /// </summary>
        public static string About_Copyright {
            get {
                return ResourceManager.GetString("About_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by Christian Krueger.
        /// </summary>
        public static string About_CreatedBy {
            get {
                return ResourceManager.GetString("About_CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to facebook.com/wp7wowarmory.
        /// </summary>
        public static string About_FacebookURL {
            get {
                return ResourceManager.GetString("About_FacebookURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow @wp7wowarmory on twitter or visit the facebook page:.
        /// </summary>
        public static string About_Links {
            get {
                return ResourceManager.GetString("About_Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit project page.
        /// </summary>
        public static string About_SourceButton {
            get {
                return ResourceManager.GetString("About_SourceButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application is open sourced and available at GitHub:.
        /// </summary>
        public static string About_SourceText {
            get {
                return ResourceManager.GetString("About_SourceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://github.com/ckrueger/WoW-Armory-for-Windows-Phone-7.
        /// </summary>
        public static string About_SourceURL {
            get {
                return ResourceManager.GetString("About_SourceURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All trademarks referenced in this application are the properties of their respective owners..
        /// </summary>
        public static string About_Trademarks {
            get {
                return ResourceManager.GetString("About_Trademarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to twitter.com/wp7wowarmory.
        /// </summary>
        public static string About_TwitterURL {
            get {
                return ResourceManager.GetString("About_TwitterURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version 2.0.
        /// </summary>
        public static string About_Version {
            get {
                return ResourceManager.GetString("About_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cataclysm Edition.
        /// </summary>
        public static string About_VersionName {
            get {
                return ResourceManager.GetString("About_VersionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World of Warcraft™ Armory.
        /// </summary>
        public static string APP_Name {
            get {
                return ResourceManager.GetString("APP_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WORLD OF WARCRAFT™ ARMORY.
        /// </summary>
        public static string APP_Name_AllCaps {
            get {
                return ResourceManager.GetString("APP_Name_AllCaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access your characters anywhere, anytime.
        /// </summary>
        public static string APP_Subname {
            get {
                return ResourceManager.GetString("APP_Subname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Death Knight.
        /// </summary>
        public static string BattleNet_Classes_DeathKnight {
            get {
                return ResourceManager.GetString("BattleNet_Classes_DeathKnight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Druid.
        /// </summary>
        public static string BattleNet_Classes_Druid {
            get {
                return ResourceManager.GetString("BattleNet_Classes_Druid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hunter.
        /// </summary>
        public static string BattleNet_Classes_Hunter {
            get {
                return ResourceManager.GetString("BattleNet_Classes_Hunter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mage.
        /// </summary>
        public static string BattleNet_Classes_Mage {
            get {
                return ResourceManager.GetString("BattleNet_Classes_Mage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paladin.
        /// </summary>
        public static string BattleNet_Classes_Paladin {
            get {
                return ResourceManager.GetString("BattleNet_Classes_Paladin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priest.
        /// </summary>
        public static string BattleNet_Classes_Priest {
            get {
                return ResourceManager.GetString("BattleNet_Classes_Priest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rogue.
        /// </summary>
        public static string BattleNet_Classes_Rogue {
            get {
                return ResourceManager.GetString("BattleNet_Classes_Rogue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shaman.
        /// </summary>
        public static string BattleNet_Classes_Shaman {
            get {
                return ResourceManager.GetString("BattleNet_Classes_Shaman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warlock.
        /// </summary>
        public static string BattleNet_Classes_Warlock {
            get {
                return ResourceManager.GetString("BattleNet_Classes_Warlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warrior.
        /// </summary>
        public static string BattleNet_Classes_Warrior {
            get {
                return ResourceManager.GetString("BattleNet_Classes_Warrior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blood Elf.
        /// </summary>
        public static string BattleNet_Races_BloodElf {
            get {
                return ResourceManager.GetString("BattleNet_Races_BloodElf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draenei.
        /// </summary>
        public static string BattleNet_Races_Draenei {
            get {
                return ResourceManager.GetString("BattleNet_Races_Draenei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dwarf.
        /// </summary>
        public static string BattleNet_Races_Dwarf {
            get {
                return ResourceManager.GetString("BattleNet_Races_Dwarf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gnome.
        /// </summary>
        public static string BattleNet_Races_Gnome {
            get {
                return ResourceManager.GetString("BattleNet_Races_Gnome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Human.
        /// </summary>
        public static string BattleNet_Races_Human {
            get {
                return ResourceManager.GetString("BattleNet_Races_Human", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night Elf.
        /// </summary>
        public static string BattleNet_Races_NightElf {
            get {
                return ResourceManager.GetString("BattleNet_Races_NightElf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orc.
        /// </summary>
        public static string BattleNet_Races_Orc {
            get {
                return ResourceManager.GetString("BattleNet_Races_Orc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tauren.
        /// </summary>
        public static string BattleNet_Races_Tauren {
            get {
                return ResourceManager.GetString("BattleNet_Races_Tauren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Troll.
        /// </summary>
        public static string BattleNet_Races_Troll {
            get {
                return ResourceManager.GetString("BattleNet_Races_Troll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undead.
        /// </summary>
        public static string BattleNet_Races_Undead {
            get {
                return ResourceManager.GetString("BattleNet_Races_Undead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string BattleNet_Realm_Population_High {
            get {
                return ResourceManager.GetString("BattleNet_Realm_Population_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string BattleNet_Realm_Population_Low {
            get {
                return ResourceManager.GetString("BattleNet_Realm_Population_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string BattleNet_Realm_Population_Medium {
            get {
                return ResourceManager.GetString("BattleNet_Realm_Population_Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not available.
        /// </summary>
        public static string BattleNet_Realm_Population_NotAvailable {
            get {
                return ResourceManager.GetString("BattleNet_Realm_Population_NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PvE.
        /// </summary>
        public static string BattleNet_Realm_Type_PvE {
            get {
                return ResourceManager.GetString("BattleNet_Realm_Type_PvE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PvP.
        /// </summary>
        public static string BattleNet_Realm_Type_PvP {
            get {
                return ResourceManager.GetString("BattleNet_Realm_Type_PvP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RP.
        /// </summary>
        public static string BattleNet_Realm_Type_RP {
            get {
                return ResourceManager.GetString("BattleNet_Realm_Type_RP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RPPvP.
        /// </summary>
        public static string BattleNet_Realm_Type_RPPvP {
            get {
                return ResourceManager.GetString("BattleNet_Realm_Type_RPPvP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Europe.
        /// </summary>
        public static string BattleNet_Region_Europe {
            get {
                return ResourceManager.GetString("BattleNet_Region_Europe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USA.
        /// </summary>
        public static string BattleNet_Region_USA {
            get {
                return ResourceManager.GetString("BattleNet_Region_USA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exalted.
        /// </summary>
        public static string BattleNet_Reputation_Exalted {
            get {
                return ResourceManager.GetString("BattleNet_Reputation_Exalted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friendly.
        /// </summary>
        public static string BattleNet_Reputation_Friendly {
            get {
                return ResourceManager.GetString("BattleNet_Reputation_Friendly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hated.
        /// </summary>
        public static string BattleNet_Reputation_Hated {
            get {
                return ResourceManager.GetString("BattleNet_Reputation_Hated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Honored.
        /// </summary>
        public static string BattleNet_Reputation_Honored {
            get {
                return ResourceManager.GetString("BattleNet_Reputation_Honored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hostile.
        /// </summary>
        public static string BattleNet_Reputation_Hostile {
            get {
                return ResourceManager.GetString("BattleNet_Reputation_Hostile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neutral.
        /// </summary>
        public static string BattleNet_Reputation_Neutral {
            get {
                return ResourceManager.GetString("BattleNet_Reputation_Neutral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revered.
        /// </summary>
        public static string BattleNet_Reputation_Revered {
            get {
                return ResourceManager.GetString("BattleNet_Reputation_Revered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfriendly.
        /// </summary>
        public static string BattleNet_Reputation_Unfriendly {
            get {
                return ResourceManager.GetString("BattleNet_Reputation_Unfriendly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search characters and manage your favorites.
        /// </summary>
        public static string Page_CharacterList_Title {
            get {
                return ResourceManager.GetString("Page_CharacterList_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for a character on the armory.
        /// </summary>
        public static string Page_CharacterSearch_Title {
            get {
                return ResourceManager.GetString("Page_CharacterSearch_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read more about this app.
        /// </summary>
        public static string Page_Help_Title {
            get {
                return ResourceManager.GetString("Page_Help_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest news for this app.
        /// </summary>
        public static string Page_News_Title {
            get {
                return ResourceManager.GetString("Page_News_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detailed realm information and status.
        /// </summary>
        public static string Page_RealmList_Title {
            get {
                return ResourceManager.GetString("Page_RealmList_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your settings.
        /// </summary>
        public static string Page_Settings_Title {
            get {
                return ResourceManager.GetString("Page_Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characters.
        /// </summary>
        public static string Pages_Main_Button_Characters {
            get {
                return ResourceManager.GetString("Pages_Main_Button_Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Pages_Main_Button_Help {
            get {
                return ResourceManager.GetString("Pages_Main_Button_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string Pages_Main_Button_News {
            get {
                return ResourceManager.GetString("Pages_Main_Button_News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realms.
        /// </summary>
        public static string Pages_Main_Button_Realms {
            get {
                return ResourceManager.GetString("Pages_Main_Button_Realms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Pages_Main_Button_Settings {
            get {
                return ResourceManager.GetString("Pages_Main_Button_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agility.
        /// </summary>
        public static string UI_CharacterDetails_Character_Description_Agility {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_Character_Description_Agility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arcane.
        /// </summary>
        public static string UI_CharacterDetails_Character_Description_ArcaneResistance {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_Character_Description_ArcaneResistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armor.
        /// </summary>
        public static string UI_CharacterDetails_Character_Description_Armor {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_Character_Description_Armor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attack Power.
        /// </summary>
        public static string UI_CharacterDetails_Character_Description_AttackPower {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_Character_Description_AttackPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block.
        /// </summary>
        public static string UI_CharacterDetails_Character_Description_Block {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_Character_Description_Block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combat Regen.
        /// </summary>
        public static string UI_CharacterDetails_Character_Description_CombatRegen {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_Character_Description_CombatRegen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crit.
        /// </summary>
        public static string UI_CharacterDetails_Character_Description_Crit {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_Character_Description_Crit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage.
        /// </summary>
        public static string UI_CharacterDetails_Character_Description_Damage {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_Character_Description_Damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodge.
        /// </summary>
        public static string UI_CharacterDetails_Character_Description_Dodge {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_Character_Description_Dodge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DPS.
        /// </summary>
        public static string UI_CharacterDetails_Character_Description_DPS {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_Character_Description_DPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expertise.
        /// </summary>
        public static string UI_CharacterDetails_Character_Description_Expertise {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_Character_Description_Expertise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fire.
        /// </summary>
        public static string UI_CharacterDetails_Character_Description_FireResistance {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_Character_Description_FireResistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frost.
        /// </summary>
        public static string UI_CharacterDetails_Character_Description_FrostResistance {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_Character_Description_FrostResistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haste.
        /// </summary>
        public static string UI_CharacterDetails_Character_Description_Haste {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_Character_Description_Haste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health.
        /// </summary>
        public static string UI_CharacterDetails_Character_Description_Health {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_Character_Description_Health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hit.
        /// </summary>
        public static string UI_CharacterDetails_Character_Description_Hit {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_Character_Description_Hit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intellect.
        /// </summary>
        public static string UI_CharacterDetails_Character_Description_Intellect {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_Character_Description_Intellect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mana Regen.
        /// </summary>
        public static string UI_CharacterDetails_Character_Description_ManaRegen {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_Character_Description_ManaRegen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mastery.
        /// </summary>
        public static string UI_CharacterDetails_Character_Description_Mastery {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_Character_Description_Mastery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nature.
        /// </summary>
        public static string UI_CharacterDetails_Character_Description_NatureResistance {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_Character_Description_NatureResistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parry.
        /// </summary>
        public static string UI_CharacterDetails_Character_Description_Parry {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_Character_Description_Parry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Penetration.
        /// </summary>
        public static string UI_CharacterDetails_Character_Description_Penetration {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_Character_Description_Penetration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resilience.
        /// </summary>
        public static string UI_CharacterDetails_Character_Description_Resilience {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_Character_Description_Resilience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shadow.
        /// </summary>
        public static string UI_CharacterDetails_Character_Description_ShadowResistance {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_Character_Description_ShadowResistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        public static string UI_CharacterDetails_Character_Description_Speed {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_Character_Description_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spell Power.
        /// </summary>
        public static string UI_CharacterDetails_Character_Description_SpellPower {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_Character_Description_SpellPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spirit.
        /// </summary>
        public static string UI_CharacterDetails_Character_Description_Spirit {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_Character_Description_Spirit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stamina.
        /// </summary>
        public static string UI_CharacterDetails_Character_Description_Stamina {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_Character_Description_Stamina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strength.
        /// </summary>
        public static string UI_CharacterDetails_Character_Description_Strength {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_Character_Description_Strength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base.
        /// </summary>
        public static string UI_CharacterDetails_Character_Header_Base {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_Character_Header_Base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defense.
        /// </summary>
        public static string UI_CharacterDetails_Character_Header_Defense {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_Character_Header_Defense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string UI_CharacterDetails_Character_Header_General {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_Character_Header_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melee.
        /// </summary>
        public static string UI_CharacterDetails_Character_Header_Melee {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_Character_Header_Melee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranged.
        /// </summary>
        public static string UI_CharacterDetails_Character_Header_Ranged {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_Character_Header_Ranged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resistance.
        /// </summary>
        public static string UI_CharacterDetails_Character_Header_Resistance {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_Character_Header_Resistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spell.
        /// </summary>
        public static string UI_CharacterDetails_Character_Header_Spell {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_Character_Header_Spell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focus.
        /// </summary>
        public static string UI_CharacterDetails_Character_PowerType_Focus {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_Character_PowerType_Focus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mana.
        /// </summary>
        public static string UI_CharacterDetails_Character_PowerType_Mana {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_Character_PowerType_Mana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rage.
        /// </summary>
        public static string UI_CharacterDetails_Character_PowerType_Rage {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_Character_PowerType_Rage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runic power.
        /// </summary>
        public static string UI_CharacterDetails_Character_PowerType_Runicpower {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_Character_PowerType_Runicpower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to achievements.
        /// </summary>
        public static string UI_CharacterDetails_PivotItem_Achievements {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_PivotItem_Achievements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to character.
        /// </summary>
        public static string UI_CharacterDetails_PivotItem_Character {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_PivotItem_Character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to companions.
        /// </summary>
        public static string UI_CharacterDetails_PivotItem_Companions {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_PivotItem_Companions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to guild.
        /// </summary>
        public static string UI_CharacterDetails_PivotItem_Guild {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_PivotItem_Guild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mounts.
        /// </summary>
        public static string UI_CharacterDetails_PivotItem_Mounts {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_PivotItem_Mounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pets.
        /// </summary>
        public static string UI_CharacterDetails_PivotItem_Pets {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_PivotItem_Pets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to professions.
        /// </summary>
        public static string UI_CharacterDetails_PivotItem_Professions {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_PivotItem_Professions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to progression.
        /// </summary>
        public static string UI_CharacterDetails_PivotItem_Progression {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_PivotItem_Progression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reputation.
        /// </summary>
        public static string UI_CharacterDetails_PivotItem_Reputation {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_PivotItem_Reputation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to titles.
        /// </summary>
        public static string UI_CharacterDetails_PivotItem_Titles {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_PivotItem_Titles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This character has no professions.
        /// </summary>
        public static string UI_CharacterDetails_Professions_None {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_Professions_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professions.
        /// </summary>
        public static string UI_CharacterDetails_Professions_Primary {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_Professions_Primary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This character has no primary professions.
        /// </summary>
        public static string UI_CharacterDetails_Professions_Primary_None {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_Professions_Primary_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary Skills.
        /// </summary>
        public static string UI_CharacterDetails_Professions_Secondary {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_Professions_Secondary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This character has no secondary professions.
        /// </summary>
        public static string UI_CharacterDetails_Professions_Secondary_None {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_Professions_Secondary_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string UI_CharacterList_ApplicationBar_Search {
            get {
                return ResourceManager.GetString("UI_CharacterList_ApplicationBar_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character not found.
        /// </summary>
        public static string UI_CharacterSearch_Error_CharacterNotFound_Caption {
            get {
                return ResourceManager.GetString("UI_CharacterSearch_Error_CharacterNotFound_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified character could not be found.
        /// </summary>
        public static string UI_CharacterSearch_Error_CharacterNotFound_Text {
            get {
                return ResourceManager.GetString("UI_CharacterSearch_Error_CharacterNotFound_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realm not found.
        /// </summary>
        public static string UI_CharacterSearch_Error_RealmNotFound_Caption {
            get {
                return ResourceManager.GetString("UI_CharacterSearch_Error_RealmNotFound_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified realm could not be found.
        /// </summary>
        public static string UI_CharacterSearch_Error_RealmNotFound_Text {
            get {
                return ResourceManager.GetString("UI_CharacterSearch_Error_RealmNotFound_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data retrieved.
        /// </summary>
        public static string UI_CharacterSearch_Error_Unknown_Caption {
            get {
                return ResourceManager.GetString("UI_CharacterSearch_Error_Unknown_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not retrieve data from Battle.Net.
        /// </summary>
        public static string UI_CharacterSearch_Error_Unknown_Text {
            get {
                return ResourceManager.GetString("UI_CharacterSearch_Error_Unknown_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input missing.
        /// </summary>
        public static string UI_CharacterSearch_Missing_Caption {
            get {
                return ResourceManager.GetString("UI_CharacterSearch_Missing_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please sepcify a character name.
        /// </summary>
        public static string UI_CharacterSearch_MissingName_Text {
            get {
                return ResourceManager.GetString("UI_CharacterSearch_MissingName_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify a realm name.
        /// </summary>
        public static string UI_CharacterSearch_MissingRealm_Text {
            get {
                return ResourceManager.GetString("UI_CharacterSearch_MissingRealm_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character name.
        /// </summary>
        public static string UI_CharacterSearch_Name {
            get {
                return ResourceManager.GetString("UI_CharacterSearch_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realm name.
        /// </summary>
        public static string UI_CharacterSearch_Realm {
            get {
                return ResourceManager.GetString("UI_CharacterSearch_Realm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string UI_CharacterSearch_SearchCharacter {
            get {
                return ResourceManager.GetString("UI_CharacterSearch_SearchCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data retrieved.
        /// </summary>
        public static string UI_Common_Error_NoData_Caption {
            get {
                return ResourceManager.GetString("UI_Common_Error_NoData_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not retrieve any data. Please check your network connectivity..
        /// </summary>
        public static string UI_Common_Error_NoData_Text {
            get {
                return ResourceManager.GetString("UI_Common_Error_NoData_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading data....
        /// </summary>
        public static string UI_Common_LoadingData {
            get {
                return ResourceManager.GetString("UI_Common_LoadingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string UI_Help_PivotItem_About {
            get {
                return ResourceManager.GetString("UI_Help_PivotItem_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for using this app.
        /// </summary>
        public static string UI_Main_FirstTimeUsage_Caption {
            get {
                return ResourceManager.GetString("UI_Main_FirstTimeUsage_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before you continue you may want to check out the settings and set everything the way you like. The settings page will now open automatically if that&apos;s ok for you?.
        /// </summary>
        public static string UI_Main_FirstTimeUsage_Text {
            get {
                return ResourceManager.GetString("UI_Main_FirstTimeUsage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login queue!.
        /// </summary>
        public static string UI_RealmList_Queue {
            get {
                return ResourceManager.GetString("UI_RealmList_Queue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string UI_Settings_ApplicationBar_Cancel {
            get {
                return ResourceManager.GetString("UI_Settings_ApplicationBar_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string UI_Settings_ApplicationBar_Save {
            get {
                return ResourceManager.GetString("UI_Settings_ApplicationBar_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string UI_Settings_General_CharacterList_OrderBy_Level {
            get {
                return ResourceManager.GetString("UI_Settings_General_CharacterList_OrderBy_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string UI_Settings_General_CharacterList_OrderBy_Name {
            get {
                return ResourceManager.GetString("UI_Settings_General_CharacterList_OrderBy_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show welcome message again.
        /// </summary>
        public static string UI_Settings_General_IsFirstTimeUsage {
            get {
                return ResourceManager.GetString("UI_Settings_General_IsFirstTimeUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battle.Net region.
        /// </summary>
        public static string UI_Settings_General_Region {
            get {
                return ResourceManager.GetString("UI_Settings_General_Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to general.
        /// </summary>
        public static string UI_Settings_PivotItem_General {
            get {
                return ResourceManager.GetString("UI_Settings_PivotItem_General", resourceCulture);
            }
        }
    }
}
