//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WowArmory.Core.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WowArmory.Core.Languages.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ©2010 Christian Krueger. All rights reserved..
        /// </summary>
        public static string About_Copyright {
            get {
                return ResourceManager.GetString("About_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by Christian Krueger.
        /// </summary>
        public static string About_CreatedBy {
            get {
                return ResourceManager.GetString("About_CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For the latest news and development information you can follow @wp7wowarmory on twitter..
        /// </summary>
        public static string About_Links {
            get {
                return ResourceManager.GetString("About_Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All trademarks referenced in this application are the properties of their respective owners..
        /// </summary>
        public static string About_Trademarks {
            get {
                return ResourceManager.GetString("About_Trademarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version 1.3.
        /// </summary>
        public static string About_Version {
            get {
                return ResourceManager.GetString("About_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World of Warcraft™ - Armory.
        /// </summary>
        public static string Application_Title {
            get {
                return ResourceManager.GetString("Application_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WORLD OF WARCRAFT™ - ARMORY.
        /// </summary>
        public static string Application_Title_AllCaps {
            get {
                return ResourceManager.GetString("Application_Title_AllCaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en_us.
        /// </summary>
        public static string Armory_Locale {
            get {
                return ResourceManager.GetString("Armory_Locale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warrior.
        /// </summary>
        public static string Character_Class_1 {
            get {
                return ResourceManager.GetString("Character_Class_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Druid.
        /// </summary>
        public static string Character_Class_11 {
            get {
                return ResourceManager.GetString("Character_Class_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paladin.
        /// </summary>
        public static string Character_Class_2 {
            get {
                return ResourceManager.GetString("Character_Class_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hunter.
        /// </summary>
        public static string Character_Class_3 {
            get {
                return ResourceManager.GetString("Character_Class_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rogue.
        /// </summary>
        public static string Character_Class_4 {
            get {
                return ResourceManager.GetString("Character_Class_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priest.
        /// </summary>
        public static string Character_Class_5 {
            get {
                return ResourceManager.GetString("Character_Class_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Death Knight.
        /// </summary>
        public static string Character_Class_6 {
            get {
                return ResourceManager.GetString("Character_Class_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shaman.
        /// </summary>
        public static string Character_Class_7 {
            get {
                return ResourceManager.GetString("Character_Class_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mage.
        /// </summary>
        public static string Character_Class_8 {
            get {
                return ResourceManager.GetString("Character_Class_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warlock.
        /// </summary>
        public static string Character_Class_9 {
            get {
                return ResourceManager.GetString("Character_Class_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alliance.
        /// </summary>
        public static string Character_Faction_0 {
            get {
                return ResourceManager.GetString("Character_Faction_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horde.
        /// </summary>
        public static string Character_Faction_1 {
            get {
                return ResourceManager.GetString("Character_Faction_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Character_Gender_0 {
            get {
                return ResourceManager.GetString("Character_Gender_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Character_Gender_1 {
            get {
                return ResourceManager.GetString("Character_Gender_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classes.
        /// </summary>
        public static string Item_AllowableClasses {
            get {
                return ResourceManager.GetString("Item_AllowableClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Armor.
        /// </summary>
        public static string Item_Armor {
            get {
                return ResourceManager.GetString("Item_Armor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binds when equipped.
        /// </summary>
        public static string Item_Bonding_BindsOnEquip {
            get {
                return ResourceManager.GetString("Item_Bonding_BindsOnEquip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binds when picked up.
        /// </summary>
        public static string Item_Bonding_BindsOnPickup {
            get {
                return ResourceManager.GetString("Item_Bonding_BindsOnPickup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binds when used.
        /// </summary>
        public static string Item_Bonding_BindsOnUse {
            get {
                return ResourceManager.GetString("Item_Bonding_BindsOnUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equip: Increases your armor penetration rating by {0}.
        /// </summary>
        public static string Item_Bonus_ArmorPenetration {
            get {
                return ResourceManager.GetString("Item_Bonus_ArmorPenetration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equip: Increases your attack power by {0}.
        /// </summary>
        public static string Item_Bonus_AttackPower {
            get {
                return ResourceManager.GetString("Item_Bonus_AttackPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equip: Increases your shield block rating by {0}.
        /// </summary>
        public static string Item_Bonus_BlockRating {
            get {
                return ResourceManager.GetString("Item_Bonus_BlockRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equip: Increases the block value of your shield by {0}.
        /// </summary>
        public static string Item_Bonus_BlockValue {
            get {
                return ResourceManager.GetString("Item_Bonus_BlockValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equip: Improves critical strike rating by {0}.
        /// </summary>
        public static string Item_Bonus_CritRating {
            get {
                return ResourceManager.GetString("Item_Bonus_CritRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equip: Improves spell critical strike rating by {0}.
        /// </summary>
        public static string Item_Bonus_CritSpellRating {
            get {
                return ResourceManager.GetString("Item_Bonus_CritSpellRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equip: Increases defense rating by {0}.
        /// </summary>
        public static string Item_Bonus_DefenseSkillRating {
            get {
                return ResourceManager.GetString("Item_Bonus_DefenseSkillRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equip: Increases your dodge rating by {0}.
        /// </summary>
        public static string Item_Bonus_DodgeRating {
            get {
                return ResourceManager.GetString("Item_Bonus_DodgeRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equip: Increases your expertise rating by {0}.
        /// </summary>
        public static string Item_Bonus_ExpertiseRating {
            get {
                return ResourceManager.GetString("Item_Bonus_ExpertiseRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equip: Increases your feral attack power by {0}.
        /// </summary>
        public static string Item_Bonus_FeralAttackPower {
            get {
                return ResourceManager.GetString("Item_Bonus_FeralAttackPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equip: Improves haste rating by {0}.
        /// </summary>
        public static string Item_Bonus_HasteRating {
            get {
                return ResourceManager.GetString("Item_Bonus_HasteRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equip: Improves spell haste rating by {0}.
        /// </summary>
        public static string Item_Bonus_HasteSpellRating {
            get {
                return ResourceManager.GetString("Item_Bonus_HasteSpellRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equip: Increases your health regeneration by {0}.
        /// </summary>
        public static string Item_Bonus_HealthRegen {
            get {
                return ResourceManager.GetString("Item_Bonus_HealthRegen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equip: Improves hit rating by {0}.
        /// </summary>
        public static string Item_Bonus_HitRating {
            get {
                return ResourceManager.GetString("Item_Bonus_HitRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equip: Improves spell hit rating by {0}.
        /// </summary>
        public static string Item_Bonus_HitSpellRating {
            get {
                return ResourceManager.GetString("Item_Bonus_HitSpellRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equip: Improves hit avoidance rating by {0}.
        /// </summary>
        public static string Item_Bonus_HitTakenRating {
            get {
                return ResourceManager.GetString("Item_Bonus_HitTakenRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equip: Restores {0} mana per 5 secs.
        /// </summary>
        public static string Item_Bonus_ManaRegen {
            get {
                return ResourceManager.GetString("Item_Bonus_ManaRegen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equip: Increases your parry rating by {0}.
        /// </summary>
        public static string Item_Bonus_ParryRating {
            get {
                return ResourceManager.GetString("Item_Bonus_ParryRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equip: Increases your ranged attack power by {0}.
        /// </summary>
        public static string Item_Bonus_RangedAttackPower {
            get {
                return ResourceManager.GetString("Item_Bonus_RangedAttackPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equip: Improves your resilience rating by {0}.
        /// </summary>
        public static string Item_Bonus_ResilienceRating {
            get {
                return ResourceManager.GetString("Item_Bonus_ResilienceRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equip: Increases spell penetration by {0}.
        /// </summary>
        public static string Item_Bonus_SpellPenetration {
            get {
                return ResourceManager.GetString("Item_Bonus_SpellPenetration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equip: Increases spell power by {0}.
        /// </summary>
        public static string Item_Bonus_SpellPower {
            get {
                return ResourceManager.GetString("Item_Bonus_SpellPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +{0} Agility.
        /// </summary>
        public static string Item_BonusAgility {
            get {
                return ResourceManager.GetString("Item_BonusAgility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +{0} Intellect.
        /// </summary>
        public static string Item_BonusIntellect {
            get {
                return ResourceManager.GetString("Item_BonusIntellect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +{0} Spirit.
        /// </summary>
        public static string Item_BonusSpirit {
            get {
                return ResourceManager.GetString("Item_BonusSpirit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +{0} Stamina.
        /// </summary>
        public static string Item_BonusStamina {
            get {
                return ResourceManager.GetString("Item_BonusStamina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +{0} Strength.
        /// </summary>
        public static string Item_BonusStrength {
            get {
                return ResourceManager.GetString("Item_BonusStrength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage.
        /// </summary>
        public static string Item_Damage {
            get {
                return ResourceManager.GetString("Item_Damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to damage per second.
        /// </summary>
        public static string Item_Damage_DamagePerSecond {
            get {
                return ResourceManager.GetString("Item_Damage_DamagePerSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        public static string Item_Damage_Speed {
            get {
                return ResourceManager.GetString("Item_Damage_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string Item_DropRate_0 {
            get {
                return ResourceManager.GetString("Item_DropRate_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extremely Low (1% - 2%).
        /// </summary>
        public static string Item_DropRate_1 {
            get {
                return ResourceManager.GetString("Item_DropRate_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very Low (3% - 14%).
        /// </summary>
        public static string Item_DropRate_2 {
            get {
                return ResourceManager.GetString("Item_DropRate_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low (15% - 24%).
        /// </summary>
        public static string Item_DropRate_3 {
            get {
                return ResourceManager.GetString("Item_DropRate_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium (25% - 50%).
        /// </summary>
        public static string Item_DropRate_4 {
            get {
                return ResourceManager.GetString("Item_DropRate_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High (51% - 99%).
        /// </summary>
        public static string Item_DropRate_5 {
            get {
                return ResourceManager.GetString("Item_DropRate_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guaranteed (100%).
        /// </summary>
        public static string Item_DropRate_6 {
            get {
                return ResourceManager.GetString("Item_DropRate_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durability: {0} / {1}.
        /// </summary>
        public static string Item_Durability {
            get {
                return ResourceManager.GetString("Item_Durability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heroic.
        /// </summary>
        public static string Item_Heroic {
            get {
                return ResourceManager.GetString("Item_Heroic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Item_InventoryType_Back {
            get {
                return ResourceManager.GetString("Item_InventoryType_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Item_InventoryType_Bag {
            get {
                return ResourceManager.GetString("Item_InventoryType_Bag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chest.
        /// </summary>
        public static string Item_InventoryType_Chest {
            get {
                return ResourceManager.GetString("Item_InventoryType_Chest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chest.
        /// </summary>
        public static string Item_InventoryType_Chest2 {
            get {
                return ResourceManager.GetString("Item_InventoryType_Chest2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feet.
        /// </summary>
        public static string Item_InventoryType_Feet {
            get {
                return ResourceManager.GetString("Item_InventoryType_Feet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finger.
        /// </summary>
        public static string Item_InventoryType_Finger {
            get {
                return ResourceManager.GetString("Item_InventoryType_Finger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hand.
        /// </summary>
        public static string Item_InventoryType_Hand {
            get {
                return ResourceManager.GetString("Item_InventoryType_Hand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head.
        /// </summary>
        public static string Item_InventoryType_Head {
            get {
                return ResourceManager.GetString("Item_InventoryType_Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Held On Off Hand.
        /// </summary>
        public static string Item_InventoryType_HeldOffHand {
            get {
                return ResourceManager.GetString("Item_InventoryType_HeldOffHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legs.
        /// </summary>
        public static string Item_InventoryType_Legs {
            get {
                return ResourceManager.GetString("Item_InventoryType_Legs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Hand.
        /// </summary>
        public static string Item_InventoryType_MainHand {
            get {
                return ResourceManager.GetString("Item_InventoryType_MainHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neck.
        /// </summary>
        public static string Item_InventoryType_Neck {
            get {
                return ResourceManager.GetString("Item_InventoryType_Neck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Item_InventoryType_NonEquip {
            get {
                return ResourceManager.GetString("Item_InventoryType_NonEquip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off Hand.
        /// </summary>
        public static string Item_InventoryType_OffHand {
            get {
                return ResourceManager.GetString("Item_InventoryType_OffHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off Hand.
        /// </summary>
        public static string Item_InventoryType_OffHand2 {
            get {
                return ResourceManager.GetString("Item_InventoryType_OffHand2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One-Hand.
        /// </summary>
        public static string Item_InventoryType_OneHand {
            get {
                return ResourceManager.GetString("Item_InventoryType_OneHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projectile.
        /// </summary>
        public static string Item_InventoryType_Projectile {
            get {
                return ResourceManager.GetString("Item_InventoryType_Projectile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Item_InventoryType_Quiver {
            get {
                return ResourceManager.GetString("Item_InventoryType_Quiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranged.
        /// </summary>
        public static string Item_InventoryType_Ranged {
            get {
                return ResourceManager.GetString("Item_InventoryType_Ranged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranged.
        /// </summary>
        public static string Item_InventoryType_Ranged2 {
            get {
                return ResourceManager.GetString("Item_InventoryType_Ranged2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relic.
        /// </summary>
        public static string Item_InventoryType_Relic {
            get {
                return ResourceManager.GetString("Item_InventoryType_Relic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shirt.
        /// </summary>
        public static string Item_InventoryType_Shirt {
            get {
                return ResourceManager.GetString("Item_InventoryType_Shirt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shoulders.
        /// </summary>
        public static string Item_InventoryType_Shoulder {
            get {
                return ResourceManager.GetString("Item_InventoryType_Shoulder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabard.
        /// </summary>
        public static string Item_InventoryType_Tabard {
            get {
                return ResourceManager.GetString("Item_InventoryType_Tabard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thrown.
        /// </summary>
        public static string Item_InventoryType_Thrown {
            get {
                return ResourceManager.GetString("Item_InventoryType_Thrown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trinket.
        /// </summary>
        public static string Item_InventoryType_Trinket {
            get {
                return ResourceManager.GetString("Item_InventoryType_Trinket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two Hand.
        /// </summary>
        public static string Item_InventoryType_TwoHand {
            get {
                return ResourceManager.GetString("Item_InventoryType_TwoHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waist.
        /// </summary>
        public static string Item_InventoryType_Waist {
            get {
                return ResourceManager.GetString("Item_InventoryType_Waist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrist.
        /// </summary>
        public static string Item_InventoryType_Wrist {
            get {
                return ResourceManager.GetString("Item_InventoryType_Wrist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Level {0}.
        /// </summary>
        public static string Item_Level {
            get {
                return ResourceManager.GetString("Item_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique.
        /// </summary>
        public static string Item_MaxCount_Unique {
            get {
                return ResourceManager.GetString("Item_MaxCount_Unique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}-Equipped.
        /// </summary>
        public static string Item_MaxCount_UniqueEquipabble {
            get {
                return ResourceManager.GetString("Item_MaxCount_UniqueEquipabble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requires Level {0}.
        /// </summary>
        public static string Item_RequiredLevel {
            get {
                return ResourceManager.GetString("Item_RequiredLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set.
        /// </summary>
        public static string Item_Set {
            get {
                return ResourceManager.GetString("Item_Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Socket.
        /// </summary>
        public static string Item_Socket {
            get {
                return ResourceManager.GetString("Item_Socket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        public static string Item_Socket_Blue {
            get {
                return ResourceManager.GetString("Item_Socket_Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Socket Bonus.
        /// </summary>
        public static string Item_Socket_Bonus {
            get {
                return ResourceManager.GetString("Item_Socket_Bonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta.
        /// </summary>
        public static string Item_Socket_Meta {
            get {
                return ResourceManager.GetString("Item_Socket_Meta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        public static string Item_Socket_Red {
            get {
                return ResourceManager.GetString("Item_Socket_Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow.
        /// </summary>
        public static string Item_Socket_Yellow {
            get {
                return ResourceManager.GetString("Item_Socket_Yellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boss Drop.
        /// </summary>
        public static string Item_Source_bossDrop {
            get {
                return ResourceManager.GetString("Item_Source_bossDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string Item_Source_createdByPlans {
            get {
                return ResourceManager.GetString("Item_Source_createdByPlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string Item_Source_createdBySpell {
            get {
                return ResourceManager.GetString("Item_Source_createdBySpell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop.
        /// </summary>
        public static string Item_Source_creatureDrop {
            get {
                return ResourceManager.GetString("Item_Source_creatureDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herbalism.
        /// </summary>
        public static string Item_Source_creatureHerb {
            get {
                return ResourceManager.GetString("Item_Source_creatureHerb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mining.
        /// </summary>
        public static string Item_Source_creatureMine {
            get {
                return ResourceManager.GetString("Item_Source_creatureMine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skinning.
        /// </summary>
        public static string Item_Source_creatureSkin {
            get {
                return ResourceManager.GetString("Item_Source_creatureSkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string Item_Source_currency {
            get {
                return ResourceManager.GetString("Item_Source_currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reputation Reward.
        /// </summary>
        public static string Item_Source_factionReward {
            get {
                return ResourceManager.GetString("Item_Source_factionReward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chest Drop.
        /// </summary>
        public static string Item_Source_gameObjectDrop {
            get {
                return ResourceManager.GetString("Item_Source_gameObjectDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Item_Source_none {
            get {
                return ResourceManager.GetString("Item_Source_none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quest Item.
        /// </summary>
        public static string Item_Source_objQuest {
            get {
                return ResourceManager.GetString("Item_Source_objQuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pickpocket.
        /// </summary>
        public static string Item_Source_pickPocket {
            get {
                return ResourceManager.GetString("Item_Source_pickPocket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plans.
        /// </summary>
        public static string Item_Source_planForItem {
            get {
                return ResourceManager.GetString("Item_Source_planForItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quest Item.
        /// </summary>
        public static string Item_Source_providedQuest {
            get {
                return ResourceManager.GetString("Item_Source_providedQuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PvP Reward.
        /// </summary>
        public static string Item_Source_pvpReward {
            get {
                return ResourceManager.GetString("Item_Source_pvpReward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quest Reward.
        /// </summary>
        public static string Item_Source_questReward {
            get {
                return ResourceManager.GetString("Item_Source_questReward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reagent.
        /// </summary>
        public static string Item_Source_reagentSpell {
            get {
                return ResourceManager.GetString("Item_Source_reagentSpell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quest Item.
        /// </summary>
        public static string Item_Source_startsQuest {
            get {
                return ResourceManager.GetString("Item_Source_startsQuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor.
        /// </summary>
        public static string Item_Source_vendor {
            get {
                return ResourceManager.GetString("Item_Source_vendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PvP Reward.
        /// </summary>
        public static string Item_Source_vendorPvp {
            get {
                return ResourceManager.GetString("Item_Source_vendorPvp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop.
        /// </summary>
        public static string Item_Source_worldDrop {
            get {
                return ResourceManager.GetString("Item_Source_worldDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string Page_Title_Search {
            get {
                return ResourceManager.GetString("Page_Title_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search result.
        /// </summary>
        public static string Page_Title_SearchResult {
            get {
                return ResourceManager.GetString("Page_Title_SearchResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to China.
        /// </summary>
        public static string Region_China {
            get {
                return ResourceManager.GetString("Region_China", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Europe.
        /// </summary>
        public static string Region_Europe {
            get {
                return ResourceManager.GetString("Region_Europe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korea.
        /// </summary>
        public static string Region_Korea {
            get {
                return ResourceManager.GetString("Region_Korea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taiwan.
        /// </summary>
        public static string Region_Taiwan {
            get {
                return ResourceManager.GetString("Region_Taiwan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USA.
        /// </summary>
        public static string Region_USA {
            get {
                return ResourceManager.GetString("Region_USA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Europe;USA;China;Korea;Taiwan.
        /// </summary>
        public static string Regions {
            get {
                return ResourceManager.GetString("Regions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all.
        /// </summary>
        public static string SearchType_All {
            get {
                return ResourceManager.GetString("SearchType_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to arena teams.
        /// </summary>
        public static string SearchType_ArenaTeams {
            get {
                return ResourceManager.GetString("SearchType_ArenaTeams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to characters.
        /// </summary>
        public static string SearchType_Characters {
            get {
                return ResourceManager.GetString("SearchType_Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to guilds.
        /// </summary>
        public static string SearchType_Guilds {
            get {
                return ResourceManager.GetString("SearchType_Guilds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to items.
        /// </summary>
        public static string SearchType_Items {
            get {
                return ResourceManager.GetString("SearchType_Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name;Level;Achievements.
        /// </summary>
        public static string Settings_FavoritesSortBy {
            get {
                return ResourceManager.GetString("Settings_FavoritesSortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achievements.
        /// </summary>
        public static string Settings_FavoritesSortBy_Achievements {
            get {
                return ResourceManager.GetString("Settings_FavoritesSortBy_Achievements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string Settings_FavoritesSortBy_Level {
            get {
                return ResourceManager.GetString("Settings_FavoritesSortBy_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Settings_FavoritesSortBy_Name {
            get {
                return ResourceManager.GetString("Settings_FavoritesSortBy_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remove all.
        /// </summary>
        public static string UI_ApplicationBar_RemoveAll {
            get {
                return ResourceManager.GetString("UI_ApplicationBar_RemoveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string UI_ApplicationBar_Search {
            get {
                return ResourceManager.GetString("UI_ApplicationBar_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string UI_ApplicationBar_Settings {
            get {
                return ResourceManager.GetString("UI_ApplicationBar_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achievements.
        /// </summary>
        public static string UI_CharacterDetails_Achievements {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_Achievements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earned the achievement [{0}] for {1} points..
        /// </summary>
        public static string UI_CharacterDetails_ActivityText_Achievement {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_ActivityText_Achievement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}..
        /// </summary>
        public static string UI_CharacterDetails_ActivityText_Bosskill {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_ActivityText_Bosskill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed step [{0}] of achievement [{1}]..
        /// </summary>
        public static string UI_CharacterDetails_ActivityText_Criteria {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_ActivityText_Criteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earned the feat of strength [{0}]..
        /// </summary>
        public static string UI_CharacterDetails_ActivityText_FeatOfStrength {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_ActivityText_FeatOfStrength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained [{0}]..
        /// </summary>
        public static string UI_CharacterDetails_ActivityText_Loot {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_ActivityText_Loot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armor.
        /// </summary>
        public static string UI_CharacterDetails_Armor {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_Armor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributes.
        /// </summary>
        public static string UI_CharacterDetails_Attributes {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_Attributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block.
        /// </summary>
        public static string UI_CharacterDetails_Block {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_Block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus Damage.
        /// </summary>
        public static string UI_CharacterDetails_BonusDamage {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_BonusDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus Healing.
        /// </summary>
        public static string UI_CharacterDetails_BonusHealing {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_BonusHealing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boss.
        /// </summary>
        public static string UI_CharacterDetails_Boss {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_Boss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not retrieve item information from armory.
        /// </summary>
        public static string UI_CharacterDetails_CouldNotLoadItemToolTip {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_CouldNotLoadItemToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crit Chance.
        /// </summary>
        public static string UI_CharacterDetails_CritChance {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_CritChance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage.
        /// </summary>
        public static string UI_CharacterDetails_Damage {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_Damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defense.
        /// </summary>
        public static string UI_CharacterDetails_Defense {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_Defense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defenses.
        /// </summary>
        public static string UI_CharacterDetails_Defenses {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_Defenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodge.
        /// </summary>
        public static string UI_CharacterDetails_Dodge {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_Dodge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop Rate.
        /// </summary>
        public static string UI_CharacterDetails_DropRate {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_DropRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expertise.
        /// </summary>
        public static string UI_CharacterDetails_Expertise {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_Expertise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string UI_CharacterDetails_General {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haste Rating.
        /// </summary>
        public static string UI_CharacterDetails_HasteRating {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_HasteRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hit Rating.
        /// </summary>
        public static string UI_CharacterDetails_HitRating {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_HitRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mana Regen.
        /// </summary>
        public static string UI_CharacterDetails_ManaRegen {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_ManaRegen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melee.
        /// </summary>
        public static string UI_CharacterDetails_Melee {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_Melee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parry.
        /// </summary>
        public static string UI_CharacterDetails_Parry {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_Parry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to achievements.
        /// </summary>
        public static string UI_CharacterDetails_PivotItem_Achievements {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_PivotItem_Achievements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to activity.
        /// </summary>
        public static string UI_CharacterDetails_PivotItem_Activity {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_PivotItem_Activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to character.
        /// </summary>
        public static string UI_CharacterDetails_PivotItem_Character {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_PivotItem_Character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to professions.
        /// </summary>
        public static string UI_CharacterDetails_PivotItem_Professions {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_PivotItem_Professions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reputation.
        /// </summary>
        public static string UI_CharacterDetails_PivotItem_Reputation {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_PivotItem_Reputation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to statistics.
        /// </summary>
        public static string UI_CharacterDetails_PivotItem_Statistics {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_PivotItem_Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to talents.
        /// </summary>
        public static string UI_CharacterDetails_PivotItem_Talents {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_PivotItem_Talents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power.
        /// </summary>
        public static string UI_CharacterDetails_Power {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_Power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This character has no professions.
        /// </summary>
        public static string UI_CharacterDetails_Professions_None {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_Professions_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Professions.
        /// </summary>
        public static string UI_CharacterDetails_Professions_Primary {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_Professions_Primary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This character has no primary professions.
        /// </summary>
        public static string UI_CharacterDetails_Professions_Primary_None {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_Professions_Primary_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary Professions.
        /// </summary>
        public static string UI_CharacterDetails_Professions_Secondary {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_Professions_Secondary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This character has no secondary professions.
        /// </summary>
        public static string UI_CharacterDetails_Professions_Secondary_None {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_Professions_Secondary_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranged.
        /// </summary>
        public static string UI_CharacterDetails_Ranged {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_Ranged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resilience.
        /// </summary>
        public static string UI_CharacterDetails_Resilience {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_Resilience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy.
        /// </summary>
        public static string UI_CharacterDetails_SecondBarType_e {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_SecondBarType_e", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focus.
        /// </summary>
        public static string UI_CharacterDetails_SecondBarType_f {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_SecondBarType_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mana.
        /// </summary>
        public static string UI_CharacterDetails_SecondBarType_m {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_SecondBarType_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runic Power.
        /// </summary>
        public static string UI_CharacterDetails_SecondBarType_p {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_SecondBarType_p", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rage.
        /// </summary>
        public static string UI_CharacterDetails_SecondBarType_r {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_SecondBarType_r", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string UI_CharacterDetails_Source {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        public static string UI_CharacterDetails_Speed {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spell.
        /// </summary>
        public static string UI_CharacterDetails_Spell {
            get {
                return ResourceManager.GetString("UI_CharacterDetails_Spell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occured..
        /// </summary>
        public static string UI_Error_Unknown_Text {
            get {
                return ResourceManager.GetString("UI_Error_Unknown_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured.
        /// </summary>
        public static string UI_Error_Unknown_Title {
            get {
                return ResourceManager.GetString("UI_Error_Unknown_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refresh.
        /// </summary>
        public static string UI_Favorites_ContextMenuItem_Refresh {
            get {
                return ResourceManager.GetString("UI_Favorites_ContextMenuItem_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remove.
        /// </summary>
        public static string UI_Favorites_ContextMenuItem_Remove {
            get {
                return ResourceManager.GetString("UI_Favorites_ContextMenuItem_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is nothing to remove.
        /// </summary>
        public static string UI_Favorites_MessageBox_NothingToRemove_Body {
            get {
                return ResourceManager.GetString("UI_Favorites_MessageBox_NothingToRemove_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not possible.
        /// </summary>
        public static string UI_Favorites_MessageBox_NothingToRemove_Title {
            get {
                return ResourceManager.GetString("UI_Favorites_MessageBox_NothingToRemove_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All saved characters will be removed from your favorites..
        /// </summary>
        public static string UI_Favorites_MessageBox_RemoveAll_Body {
            get {
                return ResourceManager.GetString("UI_Favorites_MessageBox_RemoveAll_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove all.
        /// </summary>
        public static string UI_Favorites_MessageBox_RemoveAll_Title {
            get {
                return ResourceManager.GetString("UI_Favorites_MessageBox_RemoveAll_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} will be removed from your favorites..
        /// </summary>
        public static string UI_Favorites_MessageBox_RemoveSelected_Body {
            get {
                return ResourceManager.GetString("UI_Favorites_MessageBox_RemoveSelected_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove character.
        /// </summary>
        public static string UI_Favorites_MessageBox_RemoveSelected_Title {
            get {
                return ResourceManager.GetString("UI_Favorites_MessageBox_RemoveSelected_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to characters.
        /// </summary>
        public static string UI_PivotHeader_Characters {
            get {
                return ResourceManager.GetString("UI_PivotHeader_Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to guilds.
        /// </summary>
        public static string UI_PivotHeader_Guilds {
            get {
                return ResourceManager.GetString("UI_PivotHeader_Guilds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hated.
        /// </summary>
        public static string UI_Reputation_0 {
            get {
                return ResourceManager.GetString("UI_Reputation_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hostile.
        /// </summary>
        public static string UI_Reputation_1 {
            get {
                return ResourceManager.GetString("UI_Reputation_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfriendly.
        /// </summary>
        public static string UI_Reputation_2 {
            get {
                return ResourceManager.GetString("UI_Reputation_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neutral.
        /// </summary>
        public static string UI_Reputation_3 {
            get {
                return ResourceManager.GetString("UI_Reputation_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friendly.
        /// </summary>
        public static string UI_Reputation_4 {
            get {
                return ResourceManager.GetString("UI_Reputation_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Honored.
        /// </summary>
        public static string UI_Reputation_5 {
            get {
                return ResourceManager.GetString("UI_Reputation_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revered.
        /// </summary>
        public static string UI_Reputation_6 {
            get {
                return ResourceManager.GetString("UI_Reputation_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exalted.
        /// </summary>
        public static string UI_Reputation_7 {
            get {
                return ResourceManager.GetString("UI_Reputation_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The armory did not provide any information.
        /// </summary>
        public static string UI_Search_ArmoryError {
            get {
                return ResourceManager.GetString("UI_Search_ArmoryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not retrieve character information from armory.
        /// </summary>
        public static string UI_Search_CouldNotRetrieveCharacter {
            get {
                return ResourceManager.GetString("UI_Search_CouldNotRetrieveCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not retrieve information from armory.
        /// </summary>
        public static string UI_Search_CouldNotRetrieveInformation {
            get {
                return ResourceManager.GetString("UI_Search_CouldNotRetrieveInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armory Error.
        /// </summary>
        public static string UI_Search_CouldNotRetrieveInformation_Caption {
            get {
                return ResourceManager.GetString("UI_Search_CouldNotRetrieveInformation_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        public static string UI_Search_Name {
            get {
                return ResourceManager.GetString("UI_Search_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter at least 2 characters for the name.
        /// </summary>
        public static string UI_Search_NameLengthInvalid {
            get {
                return ResourceManager.GetString("UI_Search_NameLengthInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search input.
        /// </summary>
        public static string UI_Search_NameLengthInvalid_Caption {
            get {
                return ResourceManager.GetString("UI_Search_NameLengthInvalid_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No character found.
        /// </summary>
        public static string UI_Search_NoCharacterFound {
            get {
                return ResourceManager.GetString("UI_Search_NoCharacterFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string UI_Search_NoCharacterFound_Title {
            get {
                return ResourceManager.GetString("UI_Search_NoCharacterFound_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify a name to search for in the armory.
        /// </summary>
        public static string UI_Search_NoNameSpecified {
            get {
                return ResourceManager.GetString("UI_Search_NoNameSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search input.
        /// </summary>
        public static string UI_Search_NoNameSpecified_Caption {
            get {
                return ResourceManager.GetString("UI_Search_NoNameSpecified_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No result found.
        /// </summary>
        public static string UI_Search_NoResultFound {
            get {
                return ResourceManager.GetString("UI_Search_NoResultFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to realm (optional).
        /// </summary>
        public static string UI_Search_Realm {
            get {
                return ResourceManager.GetString("UI_Search_Realm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to region.
        /// </summary>
        public static string UI_Search_Region {
            get {
                return ResourceManager.GetString("UI_Search_Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string UI_Search_Search {
            get {
                return ResourceManager.GetString("UI_Search_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to characters.
        /// </summary>
        public static string UI_SearchResult_PivotItem_Characters {
            get {
                return ResourceManager.GetString("UI_SearchResult_PivotItem_Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to guilds.
        /// </summary>
        public static string UI_SearchResult_PivotItem_Guilds {
            get {
                return ResourceManager.GetString("UI_SearchResult_PivotItem_Guilds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Result.
        /// </summary>
        public static string UI_SearchResult_Title {
            get {
                return ResourceManager.GetString("UI_SearchResult_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEARCH RESULT.
        /// </summary>
        public static string UI_SearchResult_TitleAllCaps {
            get {
                return ResourceManager.GetString("UI_SearchResult_TitleAllCaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string UI_Settings_ApplicationBar_Cancel {
            get {
                return ResourceManager.GetString("UI_Settings_ApplicationBar_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string UI_Settings_ApplicationBar_Save {
            get {
                return ResourceManager.GetString("UI_Settings_ApplicationBar_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update character automatically.
        /// </summary>
        public static string UI_Settings_AutoUpdate {
            get {
                return ResourceManager.GetString("UI_Settings_AutoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1;2;5;7.
        /// </summary>
        public static string UI_Settings_AutoUpdateSinceLastUpdate {
            get {
                return ResourceManager.GetString("UI_Settings_AutoUpdateSinceLastUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 day.
        /// </summary>
        public static string UI_Settings_AutoUpdateSinceLastUpdate_1 {
            get {
                return ResourceManager.GetString("UI_Settings_AutoUpdateSinceLastUpdate_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 days.
        /// </summary>
        public static string UI_Settings_AutoUpdateSinceLastUpdate_2 {
            get {
                return ResourceManager.GetString("UI_Settings_AutoUpdateSinceLastUpdate_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 days.
        /// </summary>
        public static string UI_Settings_AutoUpdateSinceLastUpdate_5 {
            get {
                return ResourceManager.GetString("UI_Settings_AutoUpdateSinceLastUpdate_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 week.
        /// </summary>
        public static string UI_Settings_AutoUpdateSinceLastUpdate_7 {
            get {
                return ResourceManager.GetString("UI_Settings_AutoUpdateSinceLastUpdate_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to since last update.
        /// </summary>
        public static string UI_Settings_AutoUpdateTimeInterval {
            get {
                return ResourceManager.GetString("UI_Settings_AutoUpdateTimeInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sort favorites by.
        /// </summary>
        public static string UI_Settings_FavoritesSortBy {
            get {
                return ResourceManager.GetString("UI_Settings_FavoritesSortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string UI_Settings_PivotItem_About {
            get {
                return ResourceManager.GetString("UI_Settings_PivotItem_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to general.
        /// </summary>
        public static string UI_Settings_PivotItem_General {
            get {
                return ResourceManager.GetString("UI_Settings_PivotItem_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to region.
        /// </summary>
        public static string UI_Settings_Region {
            get {
                return ResourceManager.GetString("UI_Settings_Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string UI_Settings_Title {
            get {
                return ResourceManager.GetString("UI_Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETTINGS.
        /// </summary>
        public static string UI_Settings_TitleAllCaps {
            get {
                return ResourceManager.GetString("UI_Settings_TitleAllCaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to use auto update time interval.
        /// </summary>
        public static string UI_Settings_UseAutoUpdateTimeInterval {
            get {
                return ResourceManager.GetString("UI_Settings_UseAutoUpdateTimeInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agility.
        /// </summary>
        public static string UI_String_Agility {
            get {
                return ResourceManager.GetString("UI_String_Agility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armor.
        /// </summary>
        public static string UI_String_Armor {
            get {
                return ResourceManager.GetString("UI_String_Armor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health.
        /// </summary>
        public static string UI_String_Health {
            get {
                return ResourceManager.GetString("UI_String_Health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intellect.
        /// </summary>
        public static string UI_String_Intellect {
            get {
                return ResourceManager.GetString("UI_String_Intellect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string UI_String_Level {
            get {
                return ResourceManager.GetString("UI_String_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string UI_String_Loading {
            get {
                return ResourceManager.GetString("UI_String_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spirit.
        /// </summary>
        public static string UI_String_Spirit {
            get {
                return ResourceManager.GetString("UI_String_Spirit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stamina.
        /// </summary>
        public static string UI_String_Stamina {
            get {
                return ResourceManager.GetString("UI_String_Stamina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strength.
        /// </summary>
        public static string UI_String_Strength {
            get {
                return ResourceManager.GetString("UI_String_Strength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to optional.
        /// </summary>
        public static string UI_TextBox_Optional {
            get {
                return ResourceManager.GetString("UI_TextBox_Optional", resourceCulture);
            }
        }
    }
}
